#pragma once
/*
enum AinmDirection
{
	eDirection_Right = 0,  // 0
	eDirection_RightUp,  // 1
	eDirection_Up,  // 2
	eDirection_LeftUp,  // 3
	eDirection_Left,  // 4
	eDirection_LeftDown,  // 5
	eDirection_Down,  // 6
	eDirection_RightDown,  // 7
};
*/
enum eDirection
{
	eDirection_Right,  // 0
	eDirection_RightUp,  // 1
	eDirection_Up,  // 2
	eDirection_LeftUp,  // 3
	eDirection_Left,  // 4
	eDirection_LeftDown,  // 5
	eDirection_Down,  // 6
	eDirection_RightDown,  // 7
	eDirection_NULL,
	//	DirectionArray_Count
};

static int quadrantToDir[9] =
{
	eDirection_Right,  // 0
	eDirection_RightUp,  // 1
	eDirection_Up,  // 2
	eDirection_LeftUp,  // 3
	eDirection_Left,  // 4
	eDirection_LeftDown,  // 5
	eDirection_Down,  // 6
	eDirection_RightDown,  // 7
	eDirection_Right,  // 8
};


enum AinmMont
{
	   //NUM_MODULES	= 48,
	   //NUM_FRAMES		= 48,
	   NUM_ANIMS_ONT		= 6,

////////////////////////////////////////////////////////////////////////////////
// Sprite Anims

	   ANIM_MONT_MOUNTIDLE_DOWN			= 0,
	   ANIM_MONT_MOUNTIDLE_LEFT			= 1,
	   ANIM_MONT_MOUNTIDLE_UP				= 2,
	   ANIM_MONT_MOUNTMOVE_DOWN			= 3,
	   ANIM_MONT_MOUNTMOVE_LEFT			= 4,
	   ANIM_MONT_MOUNTMOVE_UP				= 5,
};

enum AnimPlayer
{
	   //NUM_MODULES	= 359,
	   //NUM_FRAMES		= 358,
	   NUM_ANIMS_LAYER		= 35,

////////////////////////////////////////////////////////////////////////////////
// Sprite Anims

	   ANIM_PLAYER_ATTACK1_DOWN			= 0,
	   ANIM_PLAYER_ATTACK1_LEFT			= 1,
	   ANIM_PLAYER_ATTACK1_UP				= 2,
	   ANIM_PLAYER_ATTACK2_DOWN			= 3,
	   ANIM_PLAYER_ATTACK2_LEFT			= 4,
	   ANIM_PLAYER_ATTACK2_UP				= 5,
	   ANIM_PLAYER_ATTACK3_DOWN			= 6,
	   ANIM_PLAYER_ATTACK3_LEFT			= 7,
	   ANIM_PLAYER_ATTACK3_UP				= 8,
	   ANIM_PLAYER_ATTACK4_DOWN			= 9,
	   ANIM_PLAYER_ATTACK4_LEFT			= 10,
	   ANIM_PLAYER_ATTACK4_UP				= 11,
	   ANIM_PLAYER_ATTACK5_DOWN			= 12,
	   ANIM_PLAYER_ATTACK5_LEFT			= 13,
	   ANIM_PLAYER_ATTACK5_UP				= 14,
	   ANIM_PLAYER_ATTACK6_DOWN			= 15,
	   ANIM_PLAYER_ATTACK6_LEFT			= 16,
	   ANIM_PLAYER_ATTACK6_UP				= 17,
	   ANIM_PLAYER_DEAD_DOWN				= 18,
	   ANIM_PLAYER_DEAD_LEFT				= 19,
	   ANIM_PLAYER_DEAD_UP				= 20,
	   ANIM_PLAYER_IDLE_DOWN				= 21,
	   ANIM_PLAYER_IDLE_LEFT				= 22,
	   ANIM_PLAYER_IDLE_UP				= 23,
	   ANIM_PLAYER_MOVE_DOWN				= 24,
	   ANIM_PLAYER_MOVE_LEFT				= 25,
	   ANIM_PLAYER_MOVE_UP				= 26,
	   ANIM_PLAYER_MOUNTIDLE_DOWN			= 27,
	   ANIM_PLAYER_MOUNTIDLE_LEFT			= 28,
	   ANIM_PLAYER_MOUNTIDLE_UP			= 29,
	   ANIM_PLAYER_MOUNTMOVE_DOWN			= 30,
	   ANIM_PLAYER_MOUNTMOVE_LEFT			= 31,
	   ANIM_PLAYER_MOUNTMOVE_UP			= 32,
	   ANIM_PLAYER_SIT1_DOWN				= 33,
	   ANIM_PLAYER_SIT2_LEFT				= 34,
};

enum AinmWeapon
{
	   //NUM_MODULES	= 357,
	   //NUM_FRAMES		= 357,
	   NUM_ANIMS_P		= 35,

////////////////////////////////////////////////////////////////////////////////
// Sprite Anims

	   ANIM_WEAPON_ATTACK1_DOWN			= 0,
	   ANIM_WEAPON_ATTACK1_LEFT			= 1,
	   ANIM_WEAPON_ATTACK1_UP				= 2,
	   ANIM_WEAPON_ATTACK2_DOWN			= 3,
	   ANIM_WEAPON_ATTACK2_LEFT			= 4,
	   ANIM_WEAPON_ATTACK2_UP				= 5,
	   ANIM_WEAPON_ATTACK3_DOWN			= 6,
	   ANIM_WEAPON_ATTACK3_LEFT			= 7,
	   ANIM_WEAPON_ATTACK3_UP				= 8,
	   ANIM_WEAPON_ATTACK4_DOWN			= 9,
	   ANIM_WEAPON_ATTACK4_LEFT			= 10,
	   ANIM_WEAPON_ATTACK4_UP				= 11,
	   ANIM_WEAPON_ATTACK5_DOWN			= 12,
	   ANIM_WEAPON_ATTACK5_LEFT			= 13,
	   ANIM_WEAPON_ATTACK5_UP				= 14,
	   ANIM_WEAPON_ATTACK6_DOWN			= 15,
	   ANIM_WEAPON_ATTACK6_LEFT			= 16,
	   ANIM_WEAPON_ATTACK6_UP				= 17,
	   ANIM_WEAPON_DEAD_DOWN				= 18,
	   ANIM_WEAPON_DEAD_LEFT				= 19,
	   ANIM_WEAPON_DEAD_UP				= 20,
	   ANIM_WEAPON_IDLE_DOWN				= 21,
	   ANIM_WEAPON_IDLE_LEFT				= 22,
	   ANIM_WEAPON_IDLE_UP				= 23,
	   ANIM_WEAPON_MOVE_DOWN				= 24,
	   ANIM_WEAPON_MOVE_LEFT				= 25,
	   ANIM_WEAPON_MOVE_UP				= 26,
	   ANIM_WEAPON_MOUNTIDLE_DOWN			= 27,
	   ANIM_WEAPON_MOUNTIDLE_LEFT			= 28,
	   ANIM_WEAPON_MOUNTIDLE_UP			= 29,
	   ANIM_WEAPON_MOUNTMOVE_DOWN			= 30,
	   ANIM_WEAPON_MOUNTMOVE_LEFT			= 31,
	   ANIM_WEAPON_MOUNTMOVE_UP			= 32,
	   ANIM_WEAPON_SIT1_DOWN				= 33,
	   ANIM_WEAPON_SIT2_LEFT				= 34,
};

enum AinmMonster
{
	   //NUM_MODULES	= 108,
	   //NUM_FRAMES		= 106,
	   NUM_ANIMS_ONSTER		= 12,

////////////////////////////////////////////////////////////////////////////////
// Sprite Anims

	   ANIM_MONSTER_ATTACK_DOWN			= 0,
	   ANIM_MONSTER_ATTACK_LEFT			= 1,
	   ANIM_MONSTER_ATTACK_UP				= 2,
	   ANIM_MONSTER_DEAD_DOWN				= 3,
	   ANIM_MONSTER_DEAD_LEFT				= 4,
	   ANIM_MONSTER_DEAD_UP				= 5,
	   ANIM_MONSTER_IDLE_DOWN				= 6,
	   ANIM_MONSTER_IDLE_LEFT				= 7,
	   ANIM_MONSTER_IDLE_UP				= 8,
	   ANIM_MONSTER_MOVE_DOWN				= 9,
	   ANIM_MONSTER_MOVE_LEFT				= 10,
	   ANIM_MONSTER_MOVE_UP				= 11,
};

enum TakIcon
{
	   //NUM_MODULES	= 28,
	   //NUM_FRAMES		= 28,
	   NUM_ANIMS_KICON		= 5,

////////////////////////////////////////////////////////////////////////////////
// Sprite Anims

	   ANIM_EMPTY							= 0,
	   ANIM_ACCEPT_NORMAL					= 1,
	   ANIM_ACCEPT_DAILY					= 2,
	   ANIM_FINISH_NORMAL					= 3,
	   ANIM_FINISH_DAILY					= 4,
};

enum AinmMonsterSFX
{
	   //NUM_MODULES	= 148,
	   //NUM_FRAMES		= 148,
	   NUM_ANIMS_NSTERSFX		= 90,

////////////////////////////////////////////////////////////////////////////////
// Sprite Anims

	   ANIM_MONSTERSFX_E1_AGROUND			= 0,
	   ANIM_MONSTERSFX_E1_BODY			= 1,
	   ANIM_MONSTERSFX_E1_FLY				= 2,
	   ANIM_MONSTERSFX_E1_HGROUND			= 3,
	   ANIM_MONSTERSFX_E1_ZBODY			= 4,
	   ANIM_MONSTERSFX_E2_AGROUND			= 5,
	   ANIM_MONSTERSFX_E2_BODY			= 6,
	   ANIM_MONSTERSFX_E2_FLY				= 7,
	   ANIM_MONSTERSFX_E2_HGROUND			= 8,
	   ANIM_MONSTERSFX_E2_ZBODY			= 9,
	   ANIM_MONSTERSFX_E3_AGROUND			= 10,
	   ANIM_MONSTERSFX_E3_BODY			= 11,
	   ANIM_MONSTERSFX_E3_FLY				= 12,
	   ANIM_MONSTERSFX_E3_HGROUND			= 13,
	   ANIM_MONSTERSFX_E3_ZBODY			= 14,
	   ANIM_MONSTERSFX_E4_AGROUND			= 15,
	   ANIM_MONSTERSFX_E4_BODY			= 16,
	   ANIM_MONSTERSFX_E4_FLY				= 17,
	   ANIM_MONSTERSFX_E4_HGROUND			= 18,
	   ANIM_MONSTERSFX_E4_ZBODY			= 19,
	   ANIM_MONSTERSFX_E5_AGROUND			= 20,
	   ANIM_MONSTERSFX_E5_BODY			= 21,
	   ANIM_MONSTERSFX_E5_FLY				= 22,
	   ANIM_MONSTERSFX_E5_HGROUND			= 23,
	   ANIM_MONSTERSFX_E5_ZBODY			= 24,
	   ANIM_MONSTERSFX_E6_AGROUND			= 25,
	   ANIM_MONSTERSFX_E6_BODY			= 26,
	   ANIM_MONSTERSFX_E6_FLY				= 27,
	   ANIM_MONSTERSFX_E6_HGROUND			= 28,
	   ANIM_MONSTERSFX_E6_ZBODY			= 29,
	   ANIM_MONSTERSFX_E7_AGROUND			= 30,
	   ANIM_MONSTERSFX_E7_BODY			= 31,
	   ANIM_MONSTERSFX_E7_FLY				= 32,
	   ANIM_MONSTERSFX_E7_HGROUND			= 33,
	   ANIM_MONSTERSFX_E7_ZBODY			= 34,
	   ANIM_MONSTERSFX_E8_AGROUND			= 35,
	   ANIM_MONSTERSFX_E8_BODY			= 36,
	   ANIM_MONSTERSFX_E8_FLY				= 37,
	   ANIM_MONSTERSFX_E8_HGROUND			= 38,
	   ANIM_MONSTERSFX_E8_ZBODY			= 39,
	   ANIM_MONSTERSFX_E9_AGROUND			= 40,
	   ANIM_MONSTERSFX_E9_BODY			= 41,
	   ANIM_MONSTERSFX_E9_FLY				= 42,
	   ANIM_MONSTERSFX_E9_HGROUND			= 43,
	   ANIM_MONSTERSFX_E9_ZBODY			= 44,
	   ANIM_MONSTERSFX_E10_AGROUND		= 45,
	   ANIM_MONSTERSFX_E10_BODY			= 46,
	   ANIM_MONSTERSFX_E10_FLY			= 47,
	   ANIM_MONSTERSFX_E10_HGROUND		= 48,
	   ANIM_MONSTERSFX_E10_ZBODY			= 49,
	   ANIM_MONSTERSFX_E11_AGROUND		= 50,
	   ANIM_MONSTERSFX_E11_BODY			= 51,
	   ANIM_MONSTERSFX_E11_FLY			= 52,
	   ANIM_MONSTERSFX_E11_HGROUND		= 53,
	   ANIM_MONSTERSFX_E11_ZBODY			= 54,
	   ANIM_MONSTERSFX_E12_AGROUND		= 55,
	   ANIM_MONSTERSFX_E12_BODY			= 56,
	   ANIM_MONSTERSFX_E12_FLY			= 57,
	   ANIM_MONSTERSFX_E12_HGROUND		= 58,
	   ANIM_MONSTERSFX_E12_ZBODY			= 59,
	   ANIM_MONSTERSFX_E13_AGROUND		= 60,
	   ANIM_MONSTERSFX_E13_BODY			= 61,
	   ANIM_MONSTERSFX_E13_FLY			= 62,
	   ANIM_MONSTERSFX_E13_HGROUND		= 63,
	   ANIM_MONSTERSFX_E13_ZBODY			= 64,
	   ANIM_MONSTERSFX_E14_AGROUND		= 65,
	   ANIM_MONSTERSFX_E14_BODY			= 66,
	   ANIM_MONSTERSFX_E14_FLY			= 67,
	   ANIM_MONSTERSFX_E14_HGROUND		= 68,
	   ANIM_MONSTERSFX_E14_ZBODY			= 69,
	   ANIM_MONSTERSFX_E15_AGROUND		= 70,
	   ANIM_MONSTERSFX_E15_BODY			= 71,
	   ANIM_MONSTERSFX_E15_FLY			= 72,
	   ANIM_MONSTERSFX_E15_HGROUND		= 73,
	   ANIM_MONSTERSFX_E15_ZBODY			= 74,
	   ANIM_MONSTERSFX_E16_AGROUND		= 75,
	   ANIM_MONSTERSFX_E16_BODY			= 76,
	   ANIM_MONSTERSFX_E16_FLY			= 77,
	   ANIM_MONSTERSFX_E16_HGROUND		= 78,
	   ANIM_MONSTERSFX_E16_ZBODY			= 79,
	   ANIM_MONSTERSFX_E17_AGROUND		= 80,
	   ANIM_MONSTERSFX_E17_BODY			= 81,
	   ANIM_MONSTERSFX_E17_FLY			= 82,
	   ANIM_MONSTERSFX_E17_HGROUND		= 83,
	   ANIM_MONSTERSFX_E17_ZBODY			= 84,
	   ANIM_MONSTERSFX_E18_AGROUND		= 85,
	   ANIM_MONSTERSFX_E18_BODY			= 86,
	   ANIM_MONSTERSFX_E18_FLY			= 87,
	   ANIM_MONSTERSFX_E18_HGROUND		= 88,
	   ANIM_MONSTERSFX_E18_ZBODY			= 89,
};

enum AinmOtherSFX
{
	   //NUM_MODULES	= 344,
	   //NUM_FRAMES		= 344,
	   NUM_ANIMS_HERSFX		= 51,

////////////////////////////////////////////////////////////////////////////////
// Sprite Anims

	   ANIM_OTHERSFX_AUTOPLAY				= 0,
	   ANIM_OTHERSFX_BLOOD				= 1,
	   ANIM_OTHERSFX_BURN					= 2,
	   ANIM_OTHERSFX_CLICK				= 3,
	   ANIM_OTHERSFX_DRINK				= 4,
	   ANIM_OTHERSFX_DZ_1					= 5,
	   ANIM_OTHERSFX_DZ_2					= 6,
	   ANIM_OTHERSFX_DZ_3					= 7,
	   ANIM_OTHERSFX_ENEMY1				= 8,
	   ANIM_OTHERSFX_EQUIPLEVEL1			= 9,
	   ANIM_OTHERSFX_EQUIPLEVEL2			= 10,
	   ANIM_OTHERSFX_EQUIPLEVEL3			= 11,
	   ANIM_OTHERSFX_EQUIPLEVEL4			= 12,
	   ANIM_OTHERSFX_EQUIPLEVEL5			= 13,
	   ANIM_OTHERSFX_GOODWILL1			= 14,
	   ANIM_OTHERSFX_GOODWILL2			= 15,
	   ANIM_OTHERSFX_GOODWILL3			= 16,
	   ANIM_OTHERSFX_LEVELCOMPLETE		= 17,
	   ANIM_OTHERSFX_LEVELUP_DOWN			= 18,
	   ANIM_OTHERSFX_LEVELUP_UP			= 19,
	   ANIM_OTHERSFX_PICK					= 20,
	   ANIM_OTHERSFX_POISON				= 21,
	   ANIM_OTHERSFX_QT_1					= 22,
	   ANIM_OTHERSFX_QT_2					= 23,
	   ANIM_OTHERSFX_QT_3					= 24,
	   ANIM_OTHERSFX_QUALITYBULE			= 25,
	   ANIM_OTHERSFX_QUALITYGREEN			= 26,
	   ANIM_OTHERSFX_QUALITYPINK			= 27,
	   ANIM_OTHERSFX_QUALITYPURPLE		= 28,
	   ANIM_OTHERSFX_QUALITYYELLOW		= 29,
	   ANIM_OTHERSFX_QUESTACCEPT			= 30,
	   ANIM_OTHERSFX_QUESTCOMPLETE		= 31,
	   ANIM_OTHERSFX_REMIND50				= 32,
	   ANIM_OTHERSFX_REMIND85				= 33,
	   ANIM_OTHERSFX_SILENCE				= 34,
	   ANIM_OTHERSFX_SLOW					= 35,
	   ANIM_OTHERSFX_STAR					= 36,
	   ANIM_OTHERSFX_STUN					= 37,
	   ANIM_OTHERSFX_WAYFINDING			= 38,
	   ANIM_OTHERSFX_XINGZHEN1			= 39,
	   ANIM_OTHERSFX_XINGZHEN2			= 40,
	   ANIM_OTHERSFX_XINGZHEN3			= 41,
	   ANIM_OTHERSFX_XINGZHEN4			= 42,
	   ANIM_OTHERSFX_SHOU1				= 43,
	   ANIM_OTHERSFX_SHOU2				= 44,
	   ANIM_OTHERSFX_BAIHUADIYI			= 45,
	   ANIM_OTHERSFX_DIYIMEINV			= 46,
	   ANIM_OTHERSFX_JINWEIDIYI			= 47,
	   ANIM_OTHERSFX_SHIDAGAOSHOU			= 48,
	   ANIM_OTHERSFX_SHIDAMEINV			= 49,
	   ANIM_OTHERSFX_TIANXIADIYI			= 50,
	   ANIM_OTHERSFX_SUCCESS1           =51,
	   ANIM_OTHERSFX_SUCCESS2           =52,
	   ANIM_OTHERSFX_SUCCESS3           =53,
	   ANIM_OTHERSFX_SUCCESS4           =54,
	   ANIM_OTHERSFX_SUCCESS5           =55,
	   ANIM_OTHERSFX_SUCCESS6           =56,
	   ANIM_OTHERSFX_SUCCESS7           =57,
};

enum AinmPlayerSFX
{
	   //NUM_MODULES	= 132,
	   //NUM_FRAMES		= 132,
	   NUM_ANIMS_AYERSFX		= 90,

////////////////////////////////////////////////////////////////////////////////
// Sprite Anims

	   ANIM_PLAYERSFX_E1_AGROUND			= 0,
	   ANIM_PLAYERSFX_E1_BODY				= 1,
	   ANIM_PLAYERSFX_E1_FLY				= 2,
	   ANIM_PLAYERSFX_E1_HGROUND			= 3,
	   ANIM_PLAYERSFX_E1_ZBODY			= 4,
	   ANIM_PLAYERSFX_E2_AGROUND			= 5,
	   ANIM_PLAYERSFX_E2_BODY				= 6,
	   ANIM_PLAYERSFX_E2_FLY				= 7,
	   ANIM_PLAYERSFX_E2_HGROUND			= 8,
	   ANIM_PLAYERSFX_E2_ZBODY			= 9,
	   ANIM_PLAYERSFX_E3_AGROUND			= 10,
	   ANIM_PLAYERSFX_E3_BODY				= 11,
	   ANIM_PLAYERSFX_E3_FLY				= 12,
	   ANIM_PLAYERSFX_E3_HGROUND			= 13,
	   ANIM_PLAYERSFX_E3_ZBODY			= 14,
	   ANIM_PLAYERSFX_E4_AGROUND			= 15,
	   ANIM_PLAYERSFX_E4_BODY				= 16,
	   ANIM_PLAYERSFX_E4_FLY				= 17,
	   ANIM_PLAYERSFX_E4_HGROUND			= 18,
	   ANIM_PLAYERSFX_E4_ZBODY			= 19,
	   ANIM_PLAYERSFX_E5_AGROUND			= 20,
	   ANIM_PLAYERSFX_E5_BODY				= 21,
	   ANIM_PLAYERSFX_E5_FLY				= 22,
	   ANIM_PLAYERSFX_E5_HGROUND			= 23,
	   ANIM_PLAYERSFX_E5_ZBODY			= 24,
	   ANIM_PLAYERSFX_E6_AGROUND			= 25,
	   ANIM_PLAYERSFX_E6_BODY				= 26,
	   ANIM_PLAYERSFX_E6_FLY				= 27,
	   ANIM_PLAYERSFX_E6_HGROUND			= 28,
	   ANIM_PLAYERSFX_E6_ZBODY			= 29,
	   ANIM_PLAYERSFX_E7_AGROUND			= 30,
	   ANIM_PLAYERSFX_E7_BODY				= 31,
	   ANIM_PLAYERSFX_E7_FLY				= 32,
	   ANIM_PLAYERSFX_E7_HGROUND			= 33,
	   ANIM_PLAYERSFX_E7_ZBODY			= 34,
	   ANIM_PLAYERSFX_E8_AGROUND			= 35,
	   ANIM_PLAYERSFX_E8_BODY				= 36,
	   ANIM_PLAYERSFX_E8_FLY				= 37,
	   ANIM_PLAYERSFX_E8_HGROUND			= 38,
	   ANIM_PLAYERSFX_E8_ZBODY			= 39,
	   ANIM_PLAYERSFX_E9_AGROUND			= 40,
	   ANIM_PLAYERSFX_E9_BODY				= 41,
	   ANIM_PLAYERSFX_E9_FLY				= 42,
	   ANIM_PLAYERSFX_E9_HGROUND			= 43,
	   ANIM_PLAYERSFX_E9_ZBODY			= 44,
	   ANIM_PLAYERSFX_E10_AGROUND			= 45,
	   ANIM_PLAYERSFX_E10_BODY			= 46,
	   ANIM_PLAYERSFX_E10_FLY				= 47,
	   ANIM_PLAYERSFX_E10_HGROUND			= 48,
	   ANIM_PLAYERSFX_E10_ZBODY			= 49,
	   ANIM_PLAYERSFX_E11_AGROUND			= 50,
	   ANIM_PLAYERSFX_E11_BODY			= 51,
	   ANIM_PLAYERSFX_E11_FLY				= 52,
	   ANIM_PLAYERSFX_E11_HGROUND			= 53,
	   ANIM_PLAYERSFX_E11_ZBODY			= 54,
	   ANIM_PLAYERSFX_E12_AGROUND			= 55,
	   ANIM_PLAYERSFX_E12_BODY			= 56,
	   ANIM_PLAYERSFX_E12_FLY				= 57,
	   ANIM_PLAYERSFX_E12_HGROUND			= 58,
	   ANIM_PLAYERSFX_E12_ZBODY			= 59,
	   ANIM_PLAYERSFX_E13_AGROUND			= 60,
	   ANIM_PLAYERSFX_E13_BODY			= 61,
	   ANIM_PLAYERSFX_E13_FLY				= 62,
	   ANIM_PLAYERSFX_E13_HGROUND			= 63,
	   ANIM_PLAYERSFX_E13_ZBODY			= 64,
	   ANIM_PLAYERSFX_E14_AGROUND			= 65,
	   ANIM_PLAYERSFX_E14_BODY			= 66,
	   ANIM_PLAYERSFX_E14_FLY				= 67,
	   ANIM_PLAYERSFX_E14_HGROUND			= 68,
	   ANIM_PLAYERSFX_E14_ZBODY			= 69,
	   ANIM_PLAYERSFX_E15_AGROUND			= 70,
	   ANIM_PLAYERSFX_E15_BODY			= 71,
	   ANIM_PLAYERSFX_E15_FLY				= 72,
	   ANIM_PLAYERSFX_E15_HGROUND			= 73,
	   ANIM_PLAYERSFX_E15_ZBODY			= 74,
	   ANIM_PLAYERSFX_E16_AGROUND			= 75,
	   ANIM_PLAYERSFX_E16_BODY			= 76,
	   ANIM_PLAYERSFX_E16_FLY				= 77,
	   ANIM_PLAYERSFX_E16_HGROUND			= 78,
	   ANIM_PLAYERSFX_E16_ZBODY			= 79,
	   ANIM_PLAYERSFX_E17_AGROUND			= 80,
	   ANIM_PLAYERSFX_E17_BODY			= 81,
	   ANIM_PLAYERSFX_E17_FLY				= 82,
	   ANIM_PLAYERSFX_E17_HGROUND			= 83,
	   ANIM_PLAYERSFX_E17_ZBODY			= 84,
	   ANIM_PLAYERSFX_E18_AGROUND			= 85,
	   ANIM_PLAYERSFX_E18_BODY			= 86,
	   ANIM_PLAYERSFX_E18_FLY				= 87,
	   ANIM_PLAYERSFX_E18_HGROUND			= 88,
	   ANIM_PLAYERSFX_E18_ZBODY			= 89,
};

enum AinmXsm
{
	   //NUM_MODULES	= 175,
	   //NUM_FRAMES		= 174,
	   NUM_ANIMS_M		= 22,

////////////////////////////////////////////////////////////////////////////////
// Sprite Anims

	   ANIM_XSM_ATTACK_DOWN				= 0,
	   ANIM_XSM_ATTACK_LEFT				= 1,
	   ANIM_XSM_ATTACK_UP				= 2,
	   ANIM_XSM_DEAD_DOWN					= 3,
	   ANIM_XSM_DEAD_LEFT					= 4,
	   ANIM_XSM_DEAD_UP					= 5,
	   ANIM_XSM_IDLE_DOWN					= 6,
	   ANIM_XSM_IDLE_LEFT					= 7,
	   ANIM_XSM_IDLE_UP					= 8,
	   ANIM_XSM_MOUNTIDLE_DOWN					= 9,
	   ANIM_XSM_MOUNTIDLE_LEFT					= 10,
	   ANIM_XSM_MOUNTIDLE_UP					= 11,
	   ANIM_XSM_MOUNTMOVE_DOWN			= 12,
	   ANIM_XSM_MOUNTMOVE_LEFT			= 13,
	   ANIM_XSM_MOUNTMOVE_UP				= 14,
	   ANIM_XSM_MOVE_DOWN			= 15,
	   ANIM_XSM_MOVE_LEFT			= 16,
	   ANIM_XSM_MOVE_UP				= 17,
	   ANIM_XSM_SIT2_LEFT					= 18,
};

enum AnimFlag
{
	ANIM_FLAG_COLOUR0				= 0,
	ANIM_FLAG_COLOUR1				= 1,
	ANIM_FLAG_COLOUR2				= 2,
	ANIM_FLAG_COLOUR3				= 3,
	ANIM_FLAG_COLOUR4				= 4,
};
